programa acabado
robertobouses/dni pull request #1
Opened 2023-03-10 16:30 UTC by robertobouses

Se trata de un programa para verificar si un dni es correcto a través del cálculo de la letra

2023-03-15 19:49 UTC, canhizares requested changes

2023-03-15 19:49 UTC, canhizares commented on gestor/get_dni_id.go
> +		log.Fatal(err)
Usa el mismo sistema que aqui => https://github.com/robertobouses/dni/pull/1/files#diff-0fac61a73c410f93615fa65336d82e943c49a209e92a2ad2270da411c5132b67R22-R26

Porque si haces un log.fatal, lo que harás será parar toda tu aplicación.

2023-03-15 19:49 UTC, canhizares commented on gestor/get_dni_id.go
> +			log.Fatal(err)
Usa el mismo sistema que aqui => https://github.com/robertobouses/dni/pull/1/files#diff-0fac61a73c410f93615fa65336d82e943c49a209e92a2ad2270da411c5132b67R22-R26

Porque si haces un log.fatal, lo que harás será parar toda tu aplicación.

2023-03-15 19:49 UTC, canhizares commented on gestor/post_dni.go
> +		log.Fatal(err)
Usa el mismo sistema que aqui => https://github.com/robertobouses/dni/pull/1/files#diff-0fac61a73c410f93615fa65336d82e943c49a209e92a2ad2270da411c5132b67R22-R26

Porque si haces un log.fatal, lo que harás será parar toda tu aplicación.

2023-03-15 19:49 UTC, canhizares commented on main.go
> +	}
En el main es el único sitio donde "podemos" usar el log.Fatal, porque si alguna de estas cosas aqui fallan, no queremos que nuestra aplicación arranque, entonces hacemos el fatal para pararla de todo.

2023-03-16 00:24 UTC, robertobouses commented on main.go
> +	}
Entendido

2023-03-16 00:25 UTC, closed without merging